[package]
name = "svg2gcode"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.26"
nalgebra = "0.33.2"
svg = "0.18.0"
